#!/bin/usr/env bash

declare -a sport=(
[0]="lo(60%)"
[1]="load(70%)"
[2]="loading(100%)"
)

declare -r adv="Hello"

function ex(){
	v=$1
	for i in ${sport[@]}
	do	
		clear
		echo -ne $v
		sleep 
	done
}
clear

ex $adv



